version: 2
jobs:
  build:
    docker:
      - image: fedora:latest
    steps:
      - checkout
      - run:
          name: install dependencies
          command: yum install -y libev-devel libffi-devel meson lua-devel ninja-build libxcb-devel libxkbcommon-devel pkg-config gcc xcb-util-keysyms-devel dbus-devel findutils dbus xorg-x11-server-utils xdotool xorg-x11-server-Xvfb
      - run:
          name: Build
          command: meson -Db_coverage=true builddir && ninja -C builddir
      - run:
          name: Test
          command: ninja -C builddir test && cat builddir/meson-logs/testlog.txt
      - run:
          name: codecov
          command: cd builddir && curl -o codecov https://codecov.io/bash && chmod +x codecov && ./codecov -R .. -y .codecov.yml
