version: 2
jobs:
  build:
    docker:
      - image: fedora:latest
    steps:
      - checkout
      - run:
          name: install dependencies
          command: yum install -y libev-devel libffi-devel meson lua-devel ninja-build libxcb-devel libxkbcommon-devel pkg-config gcc xcb-util-keysyms-devel dbus-devel
      - run:
          name: Build
          command: meson -Db_coverage=true builddir && ninja -C builddir
      - run:
          name: Test
          command: ninja -C builddir test
